# controller_manager_ns: controller_manager
controller_list: 
#  - name: "jakaUr/jaka_joint_controller"
  - name: "" 
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
